# Configuration file for https://travis-ci.org
# (c) Robert Warnke
# Checked with http://lint.travis-ci.org
language: ruby
sudo: required
dist: trusty
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends swi-prolog
env:
- "TRAVIS_BUILD_DIR=./_build"
script:
- mkdir _build
- "./make.sh"
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  overwrite: true
  file: "Toki_Pona.out"
  skip_cleanup: true
  on:
    tags: true
